export component AppWindow inherits Window {
    width: 1440px;
    height: 1024px;
    background: #ffffff;

    maincanvas := Rectangle {
        width: 1440px;
        height: 1024px;
        background: #ffffff;

        centerarea := Rectangle {
            x: 300px;
            y: 0px;
            width: 1440px - 300px - 300px;
            height: 1024px;
            background: #ffffff;

            topnavigationbar := Rectangle {
                x: 0px;
                y: 0px;
                width: 840px;
                height: 60px;
                background: #eaddff;
            }

            tab-1 := Rectangle {
                x: 645px - 300px;
                y: 0px;
                width: 150px;
                height: 60px;
                background: #6750a4;
            }

            newtab := Rectangle {
                x: 812px - 300px;
                y: 8px;
                width: 44px;
                height: 44px;
                background: #4f378a;
            }

            playerbar := Rectangle {
                x: 0px;
                y: 875px;
                width: 840px;
                height: 150px;
                background: #eaddff;
            }

            play-arrow := Rectangle {
                x: 698px - 300px;
                y: 950px;
                width: 44px;
                height: 44px;
                background: #6750a4;
            }
        }

        leftsidebar := Rectangle {
            x: 0px;
            y: 0px;
            width: 300px;
            height: 1024px;
            background: #6750a4;

            options := Rectangle {
                x: 30px;
                y: 950px;
                width: 44px;
                height: 44px;
                background: #ffffff;
            }
        }

        leftsidebarextender := Rectangle {
            x: 300px;
            y: 0px;
            width: 75px;
            height: 50px;
            background: #6750a4;
        }

        rightsidebar := Rectangle {
            x: 1140px;
            y: 0px;
            width: 300px;
            height: 1024px;
            background: #6750a4;
        }

        rightsidebarextender := Rectangle {
            x: 1065px;
            y: 0px;
            width: 75px;
            height: 50px;
            background: #6750a4;
        }
    }
}